//=========================================================
// DaliCommands.h:
//
//Written by Claudio Filho
//=========================================================
#ifndef __DALICOMMANDS_H__
#define __DALICOMMANDS_H__



typedef enum
{
	// Commands for direct control
	CMD_OFF= 0x00,
	CMD_UP = 0x01,
	CMD_DOWN = 0x02,
	CMD_STEP_UP= 0x03,
	CMD_STEP_DOWN=0x04,
	CMD_SET_MAX_LEVEL=0x05,
	CMD_SET_MIN_LEVEL=0x06,
	CMD_DOWN_AND_OFF=0x07,
	CMD_ON_AND_UP=0x08,
	CMD_ENABLE_DAPC_SEQ=0x09,
	CMD_GO_TO_SCENE=0x10,
	CMD_DALI_RESET=0x20,

	// Store commands and parameters settings
	STORE_ACTUAL_IN_DTR= 0x21, // 0x22-0x29 not available
	STORE_DTR_MAX_LEVEL= 0x2A,
	STORE_DTR_MIN_LEVEL= 0x2B,
	STORE_DTR_SYS_FAILURE_LEVEL= 0x2C,
	STORE_DTR_PWR_ON_LEVEL=0x2D,
	STORE_DTR_FADE_TIME=0x2E,
	STORE_DTR_FADE_RATE=0x2F, //0x30 -0x3F not available

	STORE_DTR_SCENE=0x40, // -0x4F
	REMOVE_FROM_SCENE=0x50, // -0x5F
	CMD_ADD_TO_GROUP=0x60, // -0x6F
	CMD_REMOVE_FROM_GROUP=0x70, // -0x7F
	STORE_DTR_SHRT_ADDR=0x80,

	//Required in case of Extra Memory Banks
	CMD_ENABLE_WRITE_MEMORY=0x81, //=0x82 -0x8F not available

	// Query requests
	QUERY_STATUS=0x90,
	QUERY_CONTROL_GEAR=0x91,
	QUERY_LAMP_FAILURE=0x92,
	QUERY_LAMP_PWR_ON=0x93,
	QUERY_LIMIT_ERROR=0x94,
	QUERY_RESET_STATE=0x95,
	QUERY_MISS_SHRT_ADDR=0x96,
	QUERY_VERSION_NUMBER=0x97,
	QUERY_CONTENT_DTR=0x98,
	QUERY_DEVICE_TYPE=0x99,
	QUERY_PHYS_MIN_LEVEL=0x9A,
	QUERY_PWR_FAILURE=0x9B,
	QUERY_CONTENT_DTR1=0x9C,
	QUERY_CONTENT_DTR2=0x9D,// 0x9E-0x9F not available

	// Queries related to arc power parameters settings
	QUERY_ACTUAL_LEVEL=0xA0,
	QUERY_MAX_LEVEL=0xA1,
	QUERY_MIN_LEVEL=0xA2,
	QUERY_PWR_ON_LEVEL=0xA3,
	QUERY_SYSTEM_FAILURE_LEVEL=0xA4,
	QUERY_FADE_TIME_RATE=0xA5, // 0xA6 - 0xAF

	CMD_RANDOMISE=0xA7,
	CMD_COMPARE=0xA9,
	CMD_WITHDRAW=0xAB,

	// Queries related to system parameters settings
	QUERY_SCENE_LEVEL=0xB0,

	CMD_SEARCH_ADDRESS_H=0xB1,
	CMD_SEARCH_ADDRESS_M=0xB3,
	CMD_SEARCH_ADDRESS_L=0xB5,
	CMD_PROGRAM_SHORT_ADDRESS = 0xB7,
	CMD_VERIFY_SHORT_ADDRESS = 0xB9,

	QUERY_SHORT_ADDRESS = 0xBB,
	QUERY_PHYSICAL_SELECTION = 0xBD,


	QUERY_GROUPS_0_7=0xC0,
	QUERY_GROUPS_8_15=0xC1,
	QUERY_RANDOM_ADDRESS_H=0xC2,
	QUERY_RANDOM_ADDRESS_M=0xC3,
	QUERY_RANDOM_ADDRESS_L=0xC4, // OxC5 - 0xDF not available
	CMD_READ_MEMORY_LOCATION = 0xC5

}DALICOMMANDS;





#endif
